#SPDX-License-Identifier: MIT-0
---
# tasks file for nextcloudrce
- name: Create Nextcloud working directory
  ansible.builtin.file:
    path: "{{nextcloud_rce_dir}}"
    state: directory
    recurse: yes
  tags:
    - install

- name: Upload sql-dump
  ansible.builtin.copy:
    src: dump.sql
    dest: "{{nextcloud_rce_dir}}/dump.sql"
  tags:
    - install

- name: Create docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{nextcloud_rce_dir}}/docker-compose.yml"
  tags:
    - install

- name: Test if container is running
  ansible.builtin.shell: "docker compose ps | grep nextcloud-app-"
  args:
    chdir: "{{nextcloud_rce_dir}}"
  ignore_errors: true
  register: container_result

- name: Start containers
  ansible.builtin.shell: "docker compose up -d"
  args:
    chdir: "{{nextcloud_rce_dir}}"
  when: container_result.rc != 0
